[package]
name = "candlestick"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.43", features = ["serde"] }
plotly = "0.14.0"
serde_json = "1.0.149"
tokio-test = "0.4.5"
yahoo_finance_api = "4.1.0"
